function Hd = getfilter2
%GETFILTER2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 30-Jun-2017 15:06:51

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency valuffilfiles are in Hz.
Fs = 64;  % Sampling Frequency

N  = 2;   % Order
Fc = 30;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
